apiVersion: v1
kind: Service
metadata:
  name: hello-app-svc
  namespace: hello-app
spec:
  type: LoadBalancer # 포트포워딩 안해도됨 -> 외부에서 접근 가능
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # 컨테이너로 들어오는 트래픽을 8080 포트로 전달
